Revert "test"
This reverts commit aa7ee0470d2d5c0630d925ed2bb985f70082b8b6.

diff --git a/front-end-nextjs/dockerfile b/front-end-nextjs/dockerfile
--- a/front-end-nextjs/dockerfile
+++ b/front-end-nextjs/dockerfile
@@ -1,19 +1,32 @@
+# Use the official Node.js 18 image with Alpine Linux as the base
 FROM node:18-alpine AS base
 
+# Set the working directory to /app
 WORKDIR /app
 
+# Copy the package files to the working directory
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN \
-if [ f yarn.lock]; then yarn --frozen-lockfile; \
-elif [ -f package-lock.json ]; then npm ci; \
-elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm && pnpm i --frozen-lockfile; \
-else echo "lockfile not found." && exit 1; \
-fi
 
+# Install the dependencies
+RUN \
+    # If yarn.lock exists, install with yarn
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    # If package-lock.json exists, install with npm
+    elif [ -f package-lock.json ]; then npm ci; \
+    # If pnpm-lock.yaml exists, install with pnpm
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+    # If no lockfile exists, exit with an error
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+# Copy the source code to the working directory
 COPY . .
 
+# Build the application
 RUN npm run build
 
+# Expose the port 3000 for the server
 EXPOSE 3000
 
-CMD ["NPM", "start"]
+# Set the default command to start the server
+CMD [ "npm", "start" ]
